services:

    jamesi_notification.notifier:
        class: '%jamesi_notification.notifier_class%'
        arguments:
            ['@doctrine', '@mailer', '@templating', '%jamesi_notification.config%']
